// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ScrollForCause.Api.Database;

#nullable disable

namespace ScrollForCause.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260214173921_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ScrollForCause.Api.Database.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-4000-8000-000000000001"),
                            DisplayOrder = 1,
                            Icon = "leaf",
                            IsActive = true,
                            Name = "Environment",
                            Slug = "environment"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0002-4000-8000-000000000002"),
                            DisplayOrder = 2,
                            Icon = "book",
                            IsActive = true,
                            Name = "Education",
                            Slug = "education"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0003-4000-8000-000000000003"),
                            DisplayOrder = 3,
                            Icon = "heart",
                            IsActive = true,
                            Name = "Health",
                            Slug = "health"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0004-4000-8000-000000000004"),
                            DisplayOrder = 4,
                            Icon = "paw",
                            IsActive = true,
                            Name = "Animals",
                            Slug = "animals"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0005-4000-8000-000000000005"),
                            DisplayOrder = 5,
                            Icon = "users",
                            IsActive = true,
                            Name = "Seniors",
                            Slug = "seniors"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0006-4000-8000-000000000006"),
                            DisplayOrder = 6,
                            Icon = "star",
                            IsActive = true,
                            Name = "Youth",
                            Slug = "youth"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0007-4000-8000-000000000007"),
                            DisplayOrder = 7,
                            Icon = "shield",
                            IsActive = true,
                            Name = "Disaster Relief",
                            Slug = "disaster-relief"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0008-4000-8000-000000000008"),
                            DisplayOrder = 8,
                            Icon = "palette",
                            IsActive = true,
                            Name = "Arts & Culture",
                            Slug = "arts-culture"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0009-4000-8000-000000000009"),
                            DisplayOrder = 9,
                            Icon = "utensils",
                            IsActive = true,
                            Name = "Food Security",
                            Slug = "food-security"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0010-4000-8000-000000000010"),
                            DisplayOrder = 10,
                            Icon = "home",
                            IsActive = true,
                            Name = "Housing",
                            Slug = "housing"
                        });
                });

            modelBuilder.Entity("ScrollForCause.Api.Database.Entities.ContentReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionTaken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReporterType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("ContentType", "ContentId");

                    b.ToTable("ContentReports");
                });

            modelBuilder.Entity("ScrollForCause.Api.Database.Entities.FeedView", b =>
                {
                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("VolunteerId", "PostId");

                    b.HasIndex("PostId");

                    b.HasIndex("ViewedAt");

                    b.ToTable("FeedViews");
                });

            modelBuilder.Entity("ScrollForCause.Api.Database.Entities.Follow", b =>
                {
                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("VolunteerId", "OrganizationId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Follows");
                });

            modelBuilder.Entity("ScrollForCause.Api.Database.Entities.NotificationSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("InterestUpdate")
                        .HasColumnType("boolean");

                    b.Property<string>("NewContentDigest")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("NewInterestEmail")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "UserType")
                        .IsUnique();

                    b.ToTable("NotificationSettings");
                });

            modelBuilder.Entity("ScrollForCause.Api.Database.Entities.Opportunity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InterestCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRemote")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)");

                    b.Property<string>("LocationAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)");

                    b.Property<int?>("MinimumAge")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("RecurrenceDesc")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ScheduleType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SkillsRequired")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TimeCommitment")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("VolunteersNeeded")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsRemote");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("StartDate");

                    b.HasIndex("Status");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("Opportunities");
                });

            modelBuilder.Entity("ScrollForCause.Api.Database.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ClerkUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Ein")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("FollowerCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ClerkUserId")
                        .IsUnique();

                    b.HasIndex("Ein");

                    b.HasIndex("IsActive");

                    b.HasIndex("VerificationStatus");

                    b.HasIndex("City", "State");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("ScrollForCause.Api.Database.Entities.OrganizationCategory", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("OrganizationId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("OrganizationCategories");
                });

            modelBuilder.Entity("ScrollForCause.Api.Database.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("InterestCount")
                        .HasColumnType("integer");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("OpportunityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("SaveCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("OpportunityId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("Status");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("ScrollForCause.Api.Database.Entities.PostMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("LowResUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("OriginalUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("ProcessingStatus");

                    b.ToTable("PostMedia");
                });

            modelBuilder.Entity("ScrollForCause.Api.Database.Entities.PostTag", b =>
                {
                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tag")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("PostId", "Tag");

                    b.HasIndex("Tag");

                    b.ToTable("PostTags");
                });

            modelBuilder.Entity("ScrollForCause.Api.Database.Entities.SavedPost", b =>
                {
                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("VolunteerId", "PostId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PostId");

                    b.ToTable("SavedPosts");
                });

            modelBuilder.Entity("ScrollForCause.Api.Database.Entities.Volunteer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ClerkUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClerkUserId")
                        .IsUnique();

                    b.HasIndex("Email");

                    b.HasIndex("IsActive");

                    b.HasIndex("City", "State");

                    b.ToTable("Volunteers");
                });

            modelBuilder.Entity("ScrollForCause.Api.Database.Entities.VolunteerCategory", b =>
                {
                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("VolunteerId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("VolunteerCategories");
                });

            modelBuilder.Entity("ScrollForCause.Api.Database.Entities.VolunteerInterest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PostId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("StatusUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("OpportunityId");

                    b.HasIndex("PostId");

                    b.HasIndex("Status");

                    b.HasIndex("VolunteerId", "OpportunityId")
                        .IsUnique();

                    b.ToTable("VolunteerInterests");
                });

            modelBuilder.Entity("ScrollForCause.Api.Database.Entities.FeedView", b =>
                {
                    b.HasOne("ScrollForCause.Api.Database.Entities.Post", "Post")
                        .WithMany("FeedViews")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScrollForCause.Api.Database.Entities.Volunteer", "Volunteer")
                        .WithMany("FeedViews")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("ScrollForCause.Api.Database.Entities.Follow", b =>
                {
                    b.HasOne("ScrollForCause.Api.Database.Entities.Organization", "Organization")
                        .WithMany("Followers")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScrollForCause.Api.Database.Entities.Volunteer", "Volunteer")
                        .WithMany("Follows")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("ScrollForCause.Api.Database.Entities.Opportunity", b =>
                {
                    b.HasOne("ScrollForCause.Api.Database.Entities.Organization", "Organization")
                        .WithMany("Opportunities")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ScrollForCause.Api.Database.Entities.OrganizationCategory", b =>
                {
                    b.HasOne("ScrollForCause.Api.Database.Entities.Category", "Category")
                        .WithMany("OrganizationCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScrollForCause.Api.Database.Entities.Organization", "Organization")
                        .WithMany("OrganizationCategories")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ScrollForCause.Api.Database.Entities.Post", b =>
                {
                    b.HasOne("ScrollForCause.Api.Database.Entities.Opportunity", "Opportunity")
                        .WithMany("Posts")
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ScrollForCause.Api.Database.Entities.Organization", "Organization")
                        .WithMany("Posts")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opportunity");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ScrollForCause.Api.Database.Entities.PostMedia", b =>
                {
                    b.HasOne("ScrollForCause.Api.Database.Entities.Post", "Post")
                        .WithMany("Media")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("ScrollForCause.Api.Database.Entities.PostTag", b =>
                {
                    b.HasOne("ScrollForCause.Api.Database.Entities.Post", "Post")
                        .WithMany("Tags")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("ScrollForCause.Api.Database.Entities.SavedPost", b =>
                {
                    b.HasOne("ScrollForCause.Api.Database.Entities.Post", "Post")
                        .WithMany("SavedByVolunteers")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScrollForCause.Api.Database.Entities.Volunteer", "Volunteer")
                        .WithMany("SavedPosts")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("ScrollForCause.Api.Database.Entities.VolunteerCategory", b =>
                {
                    b.HasOne("ScrollForCause.Api.Database.Entities.Category", "Category")
                        .WithMany("VolunteerCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScrollForCause.Api.Database.Entities.Volunteer", "Volunteer")
                        .WithMany("VolunteerCategories")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("ScrollForCause.Api.Database.Entities.VolunteerInterest", b =>
                {
                    b.HasOne("ScrollForCause.Api.Database.Entities.Opportunity", "Opportunity")
                        .WithMany("VolunteerInterests")
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScrollForCause.Api.Database.Entities.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ScrollForCause.Api.Database.Entities.Volunteer", "Volunteer")
                        .WithMany("VolunteerInterests")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opportunity");

                    b.Navigation("Post");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("ScrollForCause.Api.Database.Entities.Category", b =>
                {
                    b.Navigation("OrganizationCategories");

                    b.Navigation("VolunteerCategories");
                });

            modelBuilder.Entity("ScrollForCause.Api.Database.Entities.Opportunity", b =>
                {
                    b.Navigation("Posts");

                    b.Navigation("VolunteerInterests");
                });

            modelBuilder.Entity("ScrollForCause.Api.Database.Entities.Organization", b =>
                {
                    b.Navigation("Followers");

                    b.Navigation("Opportunities");

                    b.Navigation("OrganizationCategories");

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("ScrollForCause.Api.Database.Entities.Post", b =>
                {
                    b.Navigation("FeedViews");

                    b.Navigation("Media");

                    b.Navigation("SavedByVolunteers");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("ScrollForCause.Api.Database.Entities.Volunteer", b =>
                {
                    b.Navigation("FeedViews");

                    b.Navigation("Follows");

                    b.Navigation("SavedPosts");

                    b.Navigation("VolunteerCategories");

                    b.Navigation("VolunteerInterests");
                });
#pragma warning restore 612, 618
        }
    }
}
